### ISSUE TITLE
Can't get any meta data - csv files are all Zero bytes

### ISSUE THREAD

**Issue by shabbadont** [m8r0wn/pymeta#7] opened 2021-02-04 03:49 UTC
Scanning multiple domains. The files are downloading, but the csv files are 0 bytes and don't contain any information. I've manually checked the files and there is meta data. Am I doing something wrong?

**Comment by m8r0wn** [comment] 2021-02-04 13:23
Hi @shabbadont,
Oh no! What OS are you using? it sounds like there's an issue with calling Exiftool.
\-m8r0wn

**Comment by shabbadont** [comment] 2021-02-04 13:37
Thanks for responding. I’m on OSX and have installed Exiftool as well.

**Comment by m8r0wn** [comment] 2021-02-04 14:18
@shabbadont PyMeta was designed for Debian based Linux distributions. I try to specify this in the README because of these dependency and configuration issues. However, as an OSX user myself, you should be able to use this work-around to get things running:

**Requirements**
* Exiftool installed and added to your PATH. Test with: ```#> exiftool -ver```

*If installed with ```brew install exiftool```, I believe it does this automatically but could be wrong here.*


**Work Around**
* Manually define the Exiftool location instead of using the built-in binary by replacing **pymeta/\_\_init\_\_.py** Line 108 with:
```python
cmd = "exiftool -csv {}* > {}".format(file_dir, output_file)
```

Let me know if this works for you!
\- m8r0wn

**Comment by shabbadont** [comment] 2021-02-04 18:26
I'll give it a shot and get back to you. Thanks for the help.

**Comment by m8r0wn** [comment] 2021-03-03 12:57
Closing, let me know if that workaround does the trick!
\- m8r0wn

**Closed by m8r0wn** 2021-03-03 12:57 UTC

**Comment by jkmartindale** [comment] 2021-06-03 01:38
Just ran into the same issue on Kali, using setup.py for installation. Installing exiftool via apt and then running pymeta again immediately fixed it. I'm glad this workaround gets me running, but it's bizarre. The tool 1) can't find its included exiftool and 2) immediately works after putting exiftool on PATH without any script modification.

**Comment by jkmartindale** [comment] 2021-06-03 15:09
Actually, better theory: exiftool itself has its own dependencies not provided by pymeta. Installing exiftool systemwide didn't change which exiftool binary was used, but allowed it to run successfully because dependencies were also included.

imo it might be better to remove the bundled exiftool and force people to install it themselves to ensure proper dependencies and perl are in place.

**Comment by m8r0wn** [comment] 2021-06-08 00:58
Hi @jkmartindale,

Agreed, next push ill remove the exiftool and switch to that model. Appreciate all the help here!

Thanks,
m8r0wn
